"""Deploy Tools - Deployment and infrastructure generation."""

import json
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass
class DeploymentConfig:
    """Deployment configuration."""
    app_name: str
    python_version: str = "3.11"
    port: int = 8000
    dependencies: list[str] | None = None
    env_vars: dict[str, str] | None = None
    workers: int = 1
    health_check: bool = True


class DeployTools:
    """Tools for deployment and infrastructure generation."""

    def __init__(self, workspace_path: str):
        self.workspace = Path(workspace_path)

    def dockerfile_gen(
        self,
        config: DeploymentConfig | None = None,
        output_path: str = "Dockerfile",
    ) -> str:
        """
        Generate a Dockerfile for the project.

        Args:
            config: Deployment configuration
            output_path: Path to write Dockerfile

        Returns:
            Generated Dockerfile content
        """
        if config is None:
            config = DeploymentConfig(app_name="app")

        # Detect project type
        has_requirements = (self.workspace / "requirements.txt").exists()
        has_pyproject = (self.workspace / "pyproject.toml").exists()
        has_flask = self._check_dependency("flask")
        has_fastapi = self._check_dependency("fastapi")
        has_django = self._check_dependency("django")

        # Determine base image and run command
        if has_flask:
            run_cmd = 'CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "app:app"]'
            expose = "8000"
        elif has_fastapi:
            run_cmd = 'CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]'
            expose = "8000"
        elif has_django:
            run_cmd = 'CMD ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]'
            expose = "8000"
        else:
            run_cmd = 'CMD ["python", "main.py"]'
            expose = str(config.port)

        dockerfile = f'''# Dockerfile for {config.app_name}
# Generated by MyAgent

FROM python:{config.python_version}-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \\
    gcc \\
    && rm -rf /var/lib/apt/lists/*

# First, copy dependency files
'''

        if has_pyproject:
            dockerfile += 'COPY pyproject.toml ./\n'
            dockerfile += 'RUN pip install uv && uv sync\n'
        elif has_requirements:
            dockerfile += 'COPY requirements.txt ./\n'
            dockerfile += 'RUN pip install --no-cache-dir -r requirements.txt\n'
        else:
            dockerfile += '# No dependencies file found\n'

        dockerfile += '''
# Copy application code
COPY . .

'''

        if config.health_check:
            dockerfile += f'''# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD curl -f http://localhost:{expose}/health || exit 1

'''

        dockerfile += f'''# Expose port
EXPOSE {expose}

# Run application
{run_cmd}
'''

        if output_path:
            with open(self.workspace / output_path, "w") as f:
                f.write(dockerfile)

        return dockerfile

    def compose_gen(
        self,
        service_name: str = "app",
        port: int = 8000,
        with_db: bool = False,
        db_type: str = "postgres",
        output_path: str = "docker-compose.yml",
    ) -> str:
        """
        Generate docker-compose.yml.

        Args:
            service_name: Name of the service
            port: Port to expose
            with_db: Include database
            db_type: Database type (postgres, mysql, sqlite)
            output_path: Path to write file

        Returns:
            Generated docker-compose.yml content
        """
        compose = f'''# docker-compose.yml for {service_name}
# Generated by MyAgent

services:
  {service_name}:
    build: .
    ports:
      - "{port}:{port}"
    environment:
'''

        if with_db:
            if db_type == "postgres":
                compose += f'''      - DATABASE_URL=postgresql://user:password@db:5432/{service_name}
'''
                compose += '''    depends_on:
      - db
'''
            elif db_type == "mysql":
                compose += f'''      - DATABASE_URL=mysql://user:password@db:3306/{service_name}
'''
                compose += '''    depends_on:
      - db
'''

        compose += '''    restart: unless-stopped
    volumes:
      - ./:/app
'''

        if config.health_check:
            compose += f'''
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:{port}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
'''

        if with_db:
            if db_type == "postgres":
                compose += '''
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=''' + service_name + '''
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
'''
            elif db_type == "mysql":
                compose += '''
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=''' + service_name + '''
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
'''

        if output_path:
            with open(self.workspace / output_path, "w") as f:
                f.write(compose)

        return compose

    def github_actions_gen(
        self,
        workflow_name: str = "CI",
        with_tests: bool = True,
        with_deploy: bool = False,
        output_path: str = ".github/workflows/ci.yml",
    ) -> str:
        """
        Generate GitHub Actions workflow.

        Args:
            workflow_name: Name of the workflow
            with_tests: Include test step
            with_deploy: Include deploy step
            output_path: Path to write file

        Returns:
            Generated workflow content
        """
        # Create directory
        workflow_dir = self.workspace / ".github" / "workflows"
        workflow_dir.mkdir(parents=True, exist_ok=True)

        # Build workflow using string concatenation to avoid f-string issues
        workflow = "# .github/workflows/ci.yml\n"
        workflow += "# Generated by MyAgent\n\n"
        workflow += "name: " + workflow_name + "\n\n"
        workflow += """on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

"""

        if with_tests:
            workflow += """    - name: Run tests
      run: |
        pytest --cov=. --cov-report=xml

    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
        fail_ci_if_error: false
"""

        if with_deploy:
            workflow += """
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Deploy
      run: |
        # Add your deployment commands here
        echo "Deploying..."

"""

        workflow += '''
    - name: Lint
      run: |
        pip install ruff
        ruff check .
'''

        if output_path:
            with open(self.workspace / output_path, "w") as f:
                f.write(workflow)

        return workflow

    def fly_toml_gen(
        self,
        app_name: str,
        port: int = 8080,
        with_postgres: bool = True,
        output_path: str = "fly.toml",
    ) -> str:
        """
        Generate Fly.io configuration.

        Args:
            app_name: Application name
            port: Port to expose
            with_postgres: Include Postgres
            output_path: Path to write file

        Returns:
            Generated fly.toml content
        """
        flytoml = f'''# fly.toml
# Generated by MyAgent

app = "{app_name}"
primary_region = "iad"

[build]

[env]
  PORT = "{port}"

[[services]]
  internal_port = {port}
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
'''

        if with_postgres:
            flytoml += '''

[postgres]
  image_repository = ""
  primary_region = "iad"
  count = 1
  disk = "1GB"
  volume = "pg_data"
'''

        if output_path:
            with open(self.workspace / output_path, "w") as f:
                f.write(flytoml)

        return flytoml

    def vercel_json_gen(
        self,
        output_path: str = "vercel.json",
    ) -> str:
        """
        Generate Vercel configuration.

        Args:
            output_path: Path to write file

        Returns:
            Generated vercel.json content
        """
        vercel = '''{
  "buildCommand": "pip install -r requirements.txt",
  "installCommand": "pip install -r requirements.txt",
  "framework": null,
  "devCommand": "python main.py",
  "routes": [
    {
      "src": "/(.*)",
      "dest": "main.py"
    }
  ]
}
'''

        if output_path:
            with open(self.workspace / output_path, "w") as f:
                f.write(vercel)

        return vercel

    def deploy_checklist(self) -> str:
        """
        Generate a deployment checklist.

        Returns:
            Formatted checklist
        """
        return '''## Deployment Checklist

### Pre-Deployment
- [ ] All tests passing
- [ ] No hardcoded secrets in code
- [ ] Environment variables documented
- [ ] Dependencies locked (requirements.txt or pyproject.toml)
- [ ] Health check endpoint implemented
- [ ] Error handling in place

### Infrastructure
- [ ] Dockerfile builds successfully
- [ ] docker-compose.yml works (if using containers)
- [ ] CI/CD pipeline configured
- [ ] Database migrations ready
- [ ] Secrets configured in deployment platform

### Security
- [ ] SSL/TLS enabled
- [ ] CORS configured correctly
- [ ] Rate limiting in place
- [ ] Logging configured
- [ ] Backup strategy in place

### Post-Deployment
- [ ] Smoke tests pass
- [ ] Monitoring/alerting active
- [ ] Rollback plan documented
- [ ] Runbook available
'''

    def render_render_yaml_gen(
        self,
        output_path: str = "render.yaml",
    ) -> str:
        """Generate Render configuration."""
        render = '''# render.yaml
# Generated by MyAgent

services:
  - type: web
    name: app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free

# Uncomment to add PostgreSQL
# databases:
#   - name: app-db
#     databaseName: app
#     plan: free
'''

        if output_path:
            with open(self.workspace / output_path, "w") as f:
                f.write(render)

        return render

    def _check_dependency(self, package: str) -> bool:
        """Check if a package is in requirements."""
        files = ["requirements.txt", "pyproject.toml"]
        for file in files:
            path = self.workspace / file
            if path.exists():
                try:
                    with open(path, "r") as f:
                        content = f.read()
                    if package in content:
                        return True
                except Exception:
                    pass
        return False

    def _generate_env_example(self, config: DeploymentConfig) -> str:
        """Generate .env.example file."""
        env_vars = config.env_vars or {}

        # Add common variables
        common_vars = [
            ("DATABASE_URL", "postgresql://..."),
            ("SECRET_KEY", "your-secret-key-here"),
            ("DEBUG", "false"),
            ("LOG_LEVEL", "INFO"),
        ]

        for key, value in common_vars:
            if key not in env_vars:
                env_vars[key] = value

        lines = ["# Environment Variables", "# Generated by MyAgent", ""]
        for key, value in sorted(env_vars.items()):
            lines.append(f"{key}={value}")

        return "\n".join(lines)


def get_deploy_handlers() -> dict[str, Any]:
    """Get deploy tool handlers."""
    return {
        "dockerfile": lambda **kw: DeployTools("").dockerfile_gen(**kw),
        "compose": lambda **kw: DeployTools("").compose_gen(**kw),
        "github_actions": lambda **kw: DeployTools("").github_actions_gen(**kw),
        "fly_toml": lambda **kw: DeployTools("").fly_toml_gen(**kw),
        "vercel": lambda **kw: DeployTools("").vercel_json_gen(**kw),
        "render": lambda **kw: DeployTools("").render_render_yaml_gen(**kw),
        "checklist": lambda: DeployTools("").deploy_checklist(),
    }
